### ISSUE TITLE
creating migration table: unable to open database file

### ISSUE THREAD

**Issue by devopsdymyr** [mintel/dex-k8s-authenticator#105]
I have tried to create Dex in my aws kops kubernetes cluster with reference documentation 
[k8s-auth-a81f59d4dff6](https://medium.com/preply-engineering/k8s-auth-a81f59d4dff6)
Issue from the step
helm install -n dex --namespace kube-system --values values-dex.yml charts/dex
![Screenshot from 2019-09-15 15-52-50](https://user-images.githubusercontent.com/41105507/64920105-ebc16400-d7d0-11e9-9e5b-e9ac0ae829de.png)
![Screenshot from 2019-09-15 15-53-51](https://user-images.githubusercontent.com/41105507/64920114-101d4080-d7d1-11e9-8258-0d433f046fad.png)

**Comment by nabadger** [comment]
@devopsdymyr see https://github.com/dexidp/dex/blob/master/Documentation/storage.md#configuration

This particular issue looks like a mis-configuration - it's actually an error from dex (not dex-k8s-auth).

I would not recommend using sqlite for storage - it's fine for devel but not for production (since you can't load-balance at that point).

If you are running dex inside a kubernetes cluster, I would recommend using 

```
storage:
  type: kubernetes
  config:
    inCluster: true
```

If you want to continue with the sqlite solution, you would need to modify the dex helm chart and mount a volume to allow for `/var/dex.db` to be created.

**Comment by devopsdymyr** [comment]
Thanks @nabadger 
can you provide me any documentation for setup dex in kops aws kubernetes with github integration
my email: devopsdymyr@gmail.com

**Comment by nabadger** [comment]
@devopsdymyr it's not something I've done sorry (I don't deploy on AWS or use kops). 

I would suggest that blog you linked is pretty good - but would just try using the `inCluster` solution (that will at least fix your current issue).

**Comment by devopsdymyr** [comment]
@nabadger Thanks let me try that

**Comment by devopsdymyr** [comment]
@nabadger this issue is solved  i have another issue please have look ticket 106

**Comment by Shoaib0023** [comment]
hey @nabadger if I want to continue with sqlite solution how will I proceed , can you please guide
