### ISSUE TITLE
Dex login is fluctuation some time working and not working

### ISSUE THREAD

**Issue by devopsdymyr** [mintel/dex-k8s-authenticator#106]
I have deployed dex server based on the reference https://medium.com/preply-engineering/k8s-auth-a81f59d4dff6
which is working fine for sometime and some time not reachable commands 
![image](https://user-images.githubusercontent.com/41105507/64948479-c564fc80-d894-11e9-830e-94c027d410c0.png)

![image](https://user-images.githubusercontent.com/41105507/64948405-9e0e2f80-d894-11e9-9a74-534db630b4d7.png)

![image](https://user-images.githubusercontent.com/41105507/64948515-e0d00780-d894-11e9-9a30-43f96c413295.png)

**Comment by nabadger** [comment]
@devopsdymyr we would need to see the dex and dex-k8s-authenticator configs (with any secrets redeacted), as well as full log output from dex/dex-k8s-auth.

I would not expect you to be able to curl that callback url directly - it will probably be looking for session data which would have been setup prior (i.e. via  a call to the login url instead).

It looks like to me like Dex is crashing 

- Confirm whether or not you are load-balancing with the sqlite setup or not (again, I would not recommend that and it could result in such an issue)
- Confirm whether the pods are healthy or not (are they crashing? if so that would give you this error)

**Comment by devopsdymyr** [comment]
Due to redirection url  which is solved now
