### ISSUE TITLE
client secret configuration

### ISSUE THREAD

**Issue by FuzzOli87** [mintel/dex-k8s-authenticator#29]
Hello!

I'm using dex deployed via your charts except I'm using Ambassador to serve it. I'm looking at authenticator tools and this one is the natural choice. However, I'm a bit confused on how to configure it. 

The configuration ask for a client_secret property, where would this come from?

**Comment by nabadger** [comment]
Hi @FuzzOli87 

For the Dex server component you configure `staticClients` and provide a `secret` for each client (in our case that might be 1 secret per cluster).

On the dex-k8s-authenticator side you configure the `client_secret` field for each cluster you define.

`secret` and `client_secret` need to match - they are just strings. 

You will need to provide these though and this will depend on how you deploy both components and generate the configs.

Since you're using Helm you can do this in the values.yaml or using `--set` when using `helm --upgrade` or `helm --install`

Personally I don't use helm to run dex/dex-k8s-authetnicator. Instead I'm using ansible to deploy them. Our configs are created client-side, and variables such as `secret` / `client_secret` are populated via a secrets-manager (a common example is `vault`, although we're just using `pass` along with an ansible-plugin for this).

Thanks to #28 you can also configure the `client_secret` in dex-k8s-authenticator via an environment var. I'll document this feature soon (it is already available on in the `:latest` image. It might be useful to you, but it's only applicable to dex-k8s-authenticator not dex-server.

**Comment by nabadger** [comment]
Closing for now - let me know if you still have issues.
