### ISSUE TITLE
Should we still maintain our dex chart?

### ISSUE THREAD

**Issue by nabadger** [mintel/dex-k8s-authenticator#34]
It looks like there's a Dex chart in the k8s charts repo now (not tried it yet).

https://github.com/kubernetes/charts/tree/master/stable/dex

Any thoughts on whether we should keep our own Dex chart? I don't see it requiring regular changes...but I like the idea of contributing to the official Dex chart  - or pointing people in that direction (assuming it gets maintained and takes PR's).

**Comment by nabadger** [comment]
That's a nice idea.

I'll do a comparison soon and make some notes to see how different they are.

**Comment by whereisaaron** [comment]
dex-k8s-authenticator can point to multiple clusters and dex instances, so it not really a dependency. If we test the repo 'dex' chart and it is good, then we can update our instructions to use the dex-k8s-authenticator chart together with the repo chart and drop ours. We only provided because the dex project didn't have one.

**Comment by nabadger** [comment]
Closing this for now. 

Some new documentation I'm adding now references the official chart, but I'm fine with maintaining ours for now.
