### ISSUE TITLE
Create helm charts for dex + dex-k8s-authenticator

### ISSUE THREAD

**Issue by whereisaaron** [mintel/dex-k8s-authenticator#7]
I just wanted to call out that I have created helm charts to deploy `dex` and `dex-k8s-authenticator`, optionally in their own namespace, and including RBAC. Handles arbitrary numbers of connectors (including multiple of the same type) and connector secrets.

I'll offer them here, as soon as I get a chance to write the README's.

**Comment by nabadger** [comment]
Helm charts would be great.

Can I ask how you're intending to configure the dex-k8s-authenticator (and dex for that matter) with regards to supporting multiple clusters.

Would you run 1 per cluster? and what would that instance only provide tokens for that cluster? 

We are currently running both dex and dex-k8s-authenticator outside of Kubernetes, and have it providing tokens for a few clusters (since the dex-k8s-authenticator lets you configure multiple). Whilst this works, we obviously don't get some of the benefits that you would get by running it in K8s itself.

**Comment by whereisaaron** [comment]
Hi @nabadger you can still support multiple clusters, the `dex` and `dex-k8s-authenticator` helm charts just takes a config file within its values, with any number of configured clusters.

I am using separate charts for `dex` and `dex-k8s-authenticator` so you can e.g. 
- deploy a `dex` within each cluster, and then just one `dex-k8s-authenticator` somewhere (or maybe in just two clusters with a load balancer, so you can lose a cluster), or
- deploy one `dex` and `dex-k8s-authenticator` in one cluster and use it for all clusters.

**Comment by whereisaaron** [comment]
I have added PR #9 with the helm charts and a README.

I have been testing with:
- `kube-aws` 0.9.9 and k8s 1.8.7
- `cert-manager` 0.2.3
- `nginx-ingress` 0.9
- `dex` 2.9.0
- `dex-k8s-manager` 0.0.2

**Comment by nabadger** [comment]
This is now merged - thanks again.

I'll probably add the option to support network policies shortly, and test against a 1.9 cluster.
